project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
language_mapping:
  - language_id: af_ZA
    custom_code: af
  - language_id: ar_SA
    custom_code: ar
  - language_id: ca_ES
    custom_code: ca
  - language_id: cs_CZ
    custom_code: cs
  - language_id: da_DK
    custom_code: da
  - language_id: nl_NL
    custom_code: nl
  - language_id: fi_FI
    custom_code: fi
  - language_id: fr_FR
    custom_code: fr
  - language_id: de_DE
    custom_code: de
  - language_id: el_GR
    custom_code: el
  - language_id: he_IL
    custom_code: he
  - language_id: hu_HU
    custom_code: hu
  - language_id: id_ID
    custom_code: id
  - language_id: it_IT
    custom_code: it
  - language_id: ja_JP
    custom_code: ja
  - language_id: ko_KR
    custom_code: ko
  - language_id: pt_PT
    custom_code: pt
  - language_id: ro_RO
    custom_code: ro
  - language_id: ru_RU
    custom_code: ru
  - language_id: sr_CS
    custom_code: sr
  - language_id: es_ES
    custom_code: es
  - language_id: sv_SE
    custom_code: sv
  - language_id: uk_UA
    custom_code: uk
  - language_id: vi_VN
    custom_code: vi
files:
  - source: /config/locales/client.en.yml
    translation: /config/locales/client.%two_letters_code%.yml
  - source: /config/locales/server.en.yml
    translation: /config/locales/server.%two_letters_code%.yml
